### ISSUE TITLE
Define boundary conditions for simple model

### ISSUE THREAD

**Issue by marissabrown** [THETA476/THETA#16]
def b_c (outer_rad , boundary_temp) 
""" define the temperature on the outer radius of the particle 

## **Inputs** 
- outer_rad: calls on layer_outer_radaii for the last point 

- boundary_temp: User input of the temperature at the outer radius 

## **Outputs** 
- boundary_condition: list of outer radius and temperature 
"""

**Comment by nuclearkatie** [comment]
lets replace the variable `outer_rad` with the convention `layer_outer_radii` and spell out the full function name as `boundary_conditions` or similar so no one gets confused. Thanks Marissa!

**Comment by rarmstrong3** [comment]
closed by #31
