### ISSUE TITLE
Create constant matrix (b) building function

### ISSUE THREAD

**Issue by Zach-Fiscus** [THETA476/THETA#18]
def matrix_generator_b(boundary conditions, mesh, materials)
""" This function will generate the vector of constants (b) used in solving the equation A.x=b. It will be relatively straightforward for the steady state case, but we are unsure how transients will affect this function.

inputs
--------
- boundary conditions: the condition present at the exterior of the modeled region (interior boundary is always symmetry). This boundary condition may change with time during subsequent models.
- mesh: the array of points for the physical location of nodes and the materials assigned to them
-materials: a dictionary or nested dictionaries of the materials used in the modeled region

outputs
--------
- numpy array containing the matrix used in solving the equation A.x=b
"""

**Comment by nuclearkatie** [comment]
Update `materials` variable to reflect the new choice `material_property_library` from issue #21

**Comment by gonuke** [comment]
Won't this also need to know the heat generation on your mesh? I don't see that info in the function signature anywhere.

**Comment by nuclearkatie** [comment]
closed via #34

**Comment by nuclearkatie** [comment]
closed via #34
