### ISSUE TITLE
Create matrix solver function

### ISSUE THREAD

**Issue by Zach-Fiscus** [THETA476/THETA#19]
Edited to reflect name change comments from Katie (changed x to temperature_array)
def matrix_solver(A,b):
""" This will call the built in matrix solving utility in numpy and solve the matrix equation A.x=b for x. 

inputs 
--------
- A: The matrix generated in a separate function with coefficients of temperature at each node
- b: The array of constants generated by a separate function 

outputs
---------
- temperature_array: The value of temperatures at each node at a given time
"""

**Comment by nuclearkatie** [comment]
let's replace the variable `x` with `temperature_array`
