### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nuclearkatie** [THETA476/THETA#2]
Update README with the following elements
- [x] What problem will it solve?
- [x] What is the scope of the project in terms of fidelity and complexity?
- [x] What is considered out of scope for your project?

**Comment by Zach-Fiscus** [comment]
This should be addressed by my updates, but I'm not sure how to do that thing where it links to the issue.

**Comment by gonuke** [comment]
Edit the description of the pull request to add the words "Fixes #2"
