### ISSUE TITLE
Function to generate mesh

### ISSUE THREAD

**Issue by nuclearkatie** [THETA476/THETA#20]
def generate_mesh(layer_outer_radii,nodes_per_layer)
""" This function generates an array of grid points in the radial direction, or mesh. Grid points are spaced evenly between the previous outer radii (zero for the first layer) and the specified outer radii. generate_mesh returns a single array of r values

inputs
------
- layer_outer_radii : list of radii for each layer of the fuel particle. The first layer is assumed to start at r=0
- nodes_per_layer : list with the number of grid points corresponding to each layer

outputs
-------
- mesh : a list of grid points
"""

**Comment by Zach-Fiscus** [comment]
So is the plan with this function to allow a variable number of nodes within each material? I.e. more nodes inside fueled region where things are more likely to be interesting?

**Comment by nuclearkatie** [comment]
Yes, that's why I specified both of the inputs can be a list, allowing the user to specify the number of nodes individually for each layer (layer_mesh_density, although we can change that variable name to something better)

**Comment by nuclearkatie** [comment]
updated the variable `layer_mesh_density` to `nodes_per_layer`, which we agree is more clear
