### ISSUE TITLE
Create material property function

### ISSUE THREAD

**Issue by Zach-Fiscus** [THETA476/THETA#21]
Edited to reflect name change comments from Katie
def mat_properties(materials)
""" This will generate a nested dictionary for the materials and important material properties that will be used in other functions. Material information will be stored in an external file that is read in using this function.

inputs 
------
- materials: The materials that will be used in the particular run of the program. 

outputs
-------
- material_property_library: dictionary containing the material properties for each material to be modeled.
"""

**Comment by nuclearkatie** [comment]
We need to name the dictionary that is generated by this function. What about `material_properties` or `material_property_library` ?

**Comment by zwolf2** [comment]
Could the output of this function be a list of dictionaries, with each dictionary corresponding to a separate material? Then inside each dictionary we have keys of material properties and their corresponding value.

**Comment by bcornille** [comment]
It may be worth having an entry for each "cell" (region in-between solution points) even though data will be duplicated. It could make matrix assembly easier.

**Comment by gonuke** [comment]
That's a good strategy @zwolf2.  I disagree about an entry for every "cell" of the problem.  If you know which material is in each "cell" you can easily use this list (or perhaps a dictionary, as well) to lookup the properties while building the matrix.

**Comment by Zach-Fiscus** [comment]
This has now been resolved, thanks @zwolf2 and @rarmstrong3 .
