### ISSUE TITLE
Build plotting function

### ISSUE THREAD

**Issue by Zach-Fiscus** [THETA476/THETA#23]
Edited to reflect variable name change
def temperature_plot(temperature_array, mesh)
 """ This function will generate a plot of the temperatures at each node. Hopefully it can take advantage of some preexisting plotting software.

inputs 
--------
- temperature_array: This is an array containing temperatures at each node
- mesh: An array containing the radial position for each node

outputs
-------
- A lovely plot of the temperature distribution.

**Comment by nuclearkatie** [comment]
let's replace the variable `x` with `temperature_array`

**Comment by nuclearkatie** [comment]
Closed via #33
